### ISSUE TITLE
[Feature] - Expose API for Pool Specific Properties 

### ISSUE THREAD

**Issue by spamwax** [JavaScriptDude/zfslib#2]
How do I check the health status of each zpool using this?
I am interested in monitoring my pools and sending out an email if `state` of each pool is not `ONLINE` anymore

`zpool list -o health tank` works but using this module I get a `KeyError`:

```python
pool=poolset.get_pool('tank')
pool.get_property('health')
```

**Comment by spamwax** [comment]
It seems `conn.load_poolset` skips getting properties from `zpool` and immediately invokes `zfs list`:

```python
pools=conn.load_poolset(properties=['health','ashift'])
```

Gives the folloiwng:

```
bad property list: invalid property 'health'

....

subprocess.CalledProcessError: Command '['zfs', 'list', '-Hpr', '-o', 'name,creation,health,ashift', '-t', 'all']' returned non-zero exit status 2
```

**Comment by JavaScriptDude** [comment]
Will change title to: [Feature] - Expose API for Pool Specific Properties 
Original: load_poolset doesn't distinguish between pool-specific properties and other (dataset/filesyste)-specific properties

**Comment by JavaScriptDude** [comment]
This should be doable.

This library was originally written to develop some other python tools and Pool specific properties was not a requirement for the feature set it was developed against.

I don't know when I will have time to develop this but I'll keep it in my queue.

**Comment by spamwax** [comment]
ok, thanks. I can wait. For now, all I need is the `health` status to monitor pools and send out emergency emails. I'll do that with a direct `subprocess` call

**Comment by JavaScriptDude** [comment]
The API is now updated to include zpool properties.
